### ISSUE TITLE
Fody: An unhandled exception occurred

### ISSUE THREAD

**Issue by zengyu1221** [luyikk/NetX#1]
每新建一个项目第二次生成的时候都会提示 Fody: An unhandled exception occurred
详细信息
Exception:
Member 'System.Threading.Tasks.Task`1<System.Collections.Generic.IEnumerable`1<UserService.Abstractions.DTOs.UserInfo>> UserService.Abstractions.IUserService::GetUsers(UserService.Abstractions.QueryOption.UserQueryOption)' is declared in another module and needs to be imported
Type:
System.ArgumentException
StackTrace:
   在 Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider) 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 2228
   在 Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction) 位置 C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeWriter.cs:行号 270
   在 Mono.Cecil.Cil.CodeWriter.WriteInstructions() 位置 C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeWriter.cs:行号 180
   在 Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method) 位置 C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeWriter.cs:行号 118
   在 Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method) 位置 C:\Code\Fody\cecil\Mono.Cecil.Cil\CodeWriter.cs:行号 54
   在 Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method) 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 1643
   在 Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type) 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 1635
   在 Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type) 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 1433
   在 Mono.Cecil.MetadataBuilder.AddTypes() 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 1405
   在 Mono.Cecil.MetadataBuilder.BuildTypes() 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 1259
   在 Mono.Cecil.MetadataBuilder.BuildModule() 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 1029
   在 Mono.Cecil.MetadataBuilder.BuildMetadata() 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 999
   在 Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _) 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 137
   在 Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) 位置 C:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:行号 930
   在 Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata) 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 136
   在 Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 115
   在 Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) 位置 C:\Code\Fody\cecil\Mono.Cecil\AssemblyWriter.cs:行号 77
   在 Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) 位置 C:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:行号 1119
   在 InnerWeaver.WriteModule() 位置 C:\projects\fody\FodyIsolated\ModuleWriter.cs:行号 21
   在 InnerWeaver.Execute() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 112
Source:
Mono.Cecil
TargetSite:
Mono.Cecil.MetadataToken LookupToken(Mono.Cecil.IMetadataTokenProvider)
	UserService		1

**Comment by luyikk** [comment]
1.请更新最新版本 以及使用最新的 vs
2. 实现功能的DLL里面必须有一个可用于调用功能的接口，不可以定义在其他的DLL中
详情请参考 demo
