### ISSUE TITLE
Fody: An unhandled exception occurred:

### ISSUE THREAD

**Issue by caradilin** [luyikk/NetX#2]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误		Fody: An unhandled exception occurred:
Exception:
请求的操作无法在使用用户映射区域打开的文件上执行。

Type:
System.IO.IOException
StackTrace:
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) 位置 C:\Code\Fody\cecil\Mono.Cecil\ModuleDefinition.cs:行号 1143
   在 InnerWeaver.WriteModule() 位置 C:\projects\fody\FodyIsolated\ModuleWriter.cs:行号 18
   在 InnerWeaver.Execute() 位置 C:\projects\fody\FodyIsolated\InnerWeaver.cs:行号 113
Source:
mscorlib
TargetSite:
Void WinIOError(Int32, System.String)	TCS

**Comment by caradilin** [comment]
just like it

**Comment by luyikk** [comment]
用 vs 2019

**Comment by caradilin** [comment]
现在使用的就是VS 2019 ，程序退出后，再次编译就会出错。VS/Resharper的IDEA都会出现错误。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luyikk/NetX"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月17日(星期一) 下午4:15
收件人:&nbsp;"luyikk/NetX"<NetX@noreply.github.com&gt;;
抄送:&nbsp;"2212639304"<2212639304@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [luyikk/NetX] Fody: An unhandled exception occurred: (#2)





 
用 vs 2019

**Comment by luyikk** [comment]
那说明你的 VS2019 或者 操作系统 有问题,有一个进程使用无法被关闭,你可以重启下电脑然后再试试,如果不报错了,那么你最好修复下你的电脑系统,重装下VS

**Comment by caradilin** [comment]
电脑换成新的笔记本，VS2019是刚安装了，也是报错


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luyikk/NetX"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月18日(星期二) 上午10:27
收件人:&nbsp;"luyikk/NetX"<NetX@noreply.github.com&gt;;
抄送:&nbsp;"2212639304"<2212639304@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [luyikk/NetX] Fody: An unhandled exception occurred: (#2)





 
那说明你的 VS2019 或者 操作系统 有问题,有一个进程使用无法被关闭,你可以重启下电脑然后再试试,如果不报错了,那么你最好修复下你的电脑系统,重装下VS
